//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sum", ReplyAction="http://tempuri.org/IService1/sumResponse")]
        int sum(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sum", ReplyAction="http://tempuri.org/IService1/sumResponse")]
        System.Threading.Tasks.Task<int> sumAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTraceDate", ReplyAction="http://tempuri.org/IService1/GetTraceDateResponse")]
        string[] GetTraceDate(string FromTown, System.DateTime FromTime, string ToTown, System.DateTime ToTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTraceDate", ReplyAction="http://tempuri.org/IService1/GetTraceDateResponse")]
        System.Threading.Tasks.Task<string[]> GetTraceDateAsync(string FromTown, System.DateTime FromTime, string ToTown, System.DateTime ToTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTrace", ReplyAction="http://tempuri.org/IService1/GetTraceResponse")]
        string[] GetTrace(string FromTown, string ToTown);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTrace", ReplyAction="http://tempuri.org/IService1/GetTraceResponse")]
        System.Threading.Tasks.Task<string[]> GetTraceAsync(string FromTown, string ToTown);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfServiceClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfServiceClient.ServiceReference1.IService1>, WcfServiceClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int sum(int num1, int num2) {
            return base.Channel.sum(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> sumAsync(int num1, int num2) {
            return base.Channel.sumAsync(num1, num2);
        }
        
        public string[] GetTraceDate(string FromTown, System.DateTime FromTime, string ToTown, System.DateTime ToTime) {
            return base.Channel.GetTraceDate(FromTown, FromTime, ToTown, ToTime);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTraceDateAsync(string FromTown, System.DateTime FromTime, string ToTown, System.DateTime ToTime) {
            return base.Channel.GetTraceDateAsync(FromTown, FromTime, ToTown, ToTime);
        }
        
        public string[] GetTrace(string FromTown, string ToTown) {
            return base.Channel.GetTrace(FromTown, ToTown);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTraceAsync(string FromTown, string ToTown) {
            return base.Channel.GetTraceAsync(FromTown, ToTown);
        }
    }
}
