//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sum", ReplyAction="http://tempuri.org/IService1/sumResponse")]
        int sum(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sum", ReplyAction="http://tempuri.org/IService1/sumResponse")]
        System.Threading.Tasks.Task<int> sumAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTraceDateDirection", ReplyAction="http://tempuri.org/IService1/GetTraceDateDirectionResponse")]
        string[] GetTraceDateDirection(string FromTown, System.DateTime FromTime, string ToTown, System.DateTime ToTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTraceDateDirection", ReplyAction="http://tempuri.org/IService1/GetTraceDateDirectionResponse")]
        System.Threading.Tasks.Task<string[]> GetTraceDateDirectionAsync(string FromTown, System.DateTime FromTime, string ToTown, System.DateTime ToTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTraceDateInDirection", ReplyAction="http://tempuri.org/IService1/GetTraceDateInDirectionResponse")]
        string[] GetTraceDateInDirection(string FromTown, System.DateTime FromTime, string ToTown, System.DateTime ToTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTraceDateInDirection", ReplyAction="http://tempuri.org/IService1/GetTraceDateInDirectionResponse")]
        System.Threading.Tasks.Task<string[]> GetTraceDateInDirectionAsync(string FromTown, System.DateTime FromTime, string ToTown, System.DateTime ToTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTraceInDirection", ReplyAction="http://tempuri.org/IService1/GetTraceInDirectionResponse")]
        string[] GetTraceInDirection(string FromTown, string ToTown);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTraceInDirection", ReplyAction="http://tempuri.org/IService1/GetTraceInDirectionResponse")]
        System.Threading.Tasks.Task<string[]> GetTraceInDirectionAsync(string FromTown, string ToTown);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTraceDirection", ReplyAction="http://tempuri.org/IService1/GetTraceDirectionResponse")]
        string[] GetTraceDirection(string FromTown, string ToTown);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTraceDirection", ReplyAction="http://tempuri.org/IService1/GetTraceDirectionResponse")]
        System.Threading.Tasks.Task<string[]> GetTraceDirectionAsync(string FromTown, string ToTown);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfServiceClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfServiceClient.ServiceReference1.IService1>, WcfServiceClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int sum(int num1, int num2) {
            return base.Channel.sum(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> sumAsync(int num1, int num2) {
            return base.Channel.sumAsync(num1, num2);
        }
        
        public string[] GetTraceDateDirection(string FromTown, System.DateTime FromTime, string ToTown, System.DateTime ToTime) {
            return base.Channel.GetTraceDateDirection(FromTown, FromTime, ToTown, ToTime);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTraceDateDirectionAsync(string FromTown, System.DateTime FromTime, string ToTown, System.DateTime ToTime) {
            return base.Channel.GetTraceDateDirectionAsync(FromTown, FromTime, ToTown, ToTime);
        }
        
        public string[] GetTraceDateInDirection(string FromTown, System.DateTime FromTime, string ToTown, System.DateTime ToTime) {
            return base.Channel.GetTraceDateInDirection(FromTown, FromTime, ToTown, ToTime);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTraceDateInDirectionAsync(string FromTown, System.DateTime FromTime, string ToTown, System.DateTime ToTime) {
            return base.Channel.GetTraceDateInDirectionAsync(FromTown, FromTime, ToTown, ToTime);
        }
        
        public string[] GetTraceInDirection(string FromTown, string ToTown) {
            return base.Channel.GetTraceInDirection(FromTown, ToTown);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTraceInDirectionAsync(string FromTown, string ToTown) {
            return base.Channel.GetTraceInDirectionAsync(FromTown, ToTown);
        }
        
        public string[] GetTraceDirection(string FromTown, string ToTown) {
            return base.Channel.GetTraceDirection(FromTown, ToTown);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTraceDirectionAsync(string FromTown, string ToTown) {
            return base.Channel.GetTraceDirectionAsync(FromTown, ToTown);
        }
    }
}
